name: Build and Cache

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    
    - uses: cachix/install-nix-action@v27
      with:
        nix_path: nixpkgs=channel:nixos-unstable
        extra_nix_config: |
          experimental-features = nix-command flakes
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      env:
        NIX_FIRST_BUILD_UID: 400
          
    - uses: cachix/cachix-action@v15
      with:
        name: codex-cli
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
        
    - name: Build codex
      run: |
        nix build .#codex
        nix build .#default
        # The cachix-action will automatically push the built derivations